(()=>{const BASE='https://pyncovnrhiuwmipyxfae.supabase.co';const KEY='sb_publishable_N6tfAKab0Unt6pIIbnO8YA_wpw_JHbu';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function youtubeEmbed(u){try{const x=new URL(u);let id='';if(x.hostname.includes('youtu.be'))id=x.pathname.slice(1).split('/')[0];else if(x.hostname.includes('youtube.com')){id=x.searchParams.get('v')||((x.pathname.match(/\/(shorts|embed)\/([^/?]+)/)||[])[2]||'');}return id?'https://www.youtube.com/embed/'+encodeURIComponent(id):'';}catch{return'';}}
function media(p){if(!p.media_url)return'';const u=esc(p.media_url),yt=youtubeEmbed(p.media_url);if(p.content_type==='video'){if(yt)return '<div class="cerca-media"><iframe src="'+esc(yt)+'" title="'+esc(p.title)+'" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>';return '<div class="cerca-media"><video controls preload="metadata" src="'+u+'"></video></div>';}return '<div class="cerca-media"><img src="'+u+'" alt="'+esc(p.title)+'" loading="lazy"></div>';}
function card(p){return '<article class="cerca-post '+(p.featured?'featured':'')+'">'+(p.featured?'<span class="cerca-badge">Destacado</span>':'')+'<h4>'+esc(p.title)+'</h4>'+media(p)+(p.body?'<p>'+esc(p.body).replace(/\n/g,'<br>')+'</p>':'')+(p.link_url?'<a class="cerca-link" href="'+esc(p.link_url)+'" target="_blank" rel="noopener">'+esc(p.link_label||'Ver más')+'</a>':'')+'</article>';}
function programTarget(label){return [...document.querySelectorAll('.program-grid article')].find(a=>(a.querySelector('h3')?.textContent||'').toLowerCase().includes(label));}
function target(section){const map={ninos:()=>programTarget('niños'),adolescentes:()=>programTarget('adolescentes'),jovenes:()=>programTarget('jóvenes'),senoritas:()=>programTarget('señoritas'),familia:()=>programTarget('familia'),programas:()=>programTarget('programas especiales'),oracion:()=>document.querySelector('#oracion'),devocionales:()=>document.querySelector('#devocionales .container')};return map[section]?map[section]():null;}
function generalBox(){let box=document.querySelector('#cerca-general-content');if(box)return box;const hero=document.querySelector('.hero');if(!hero)return null;const s=document.createElement('section');s.className='section cerca-general';s.id='cerca-general-content';s.innerHTML='<div class="container"><div class="section-head center"><p class="eyebrow">CERCA HOY</p><h2>Contenido para acompañarte</h2></div><div class="cerca-posts"></div></div>';hero.insertAdjacentElement('afterend',s);return s.querySelector('.cerca-posts');}
async function load(){try{const r=await fetch(BASE+'/rest/v1/content_posts?select=*&order=featured.desc,starts_at.desc',{headers:{apikey:KEY}});if(!r.ok)return;const rows=await r.json();if(!rows.length)return;const grouped={};rows.forEach(p=>(grouped[p.section]??=[]).push(p));for(const [section,posts] of Object.entries(grouped)){if(section==='general'){const b=generalBox();if(b)b.innerHTML=posts.map(card).join('');continue;}const t=target(section);if(!t)continue;let box=t.querySelector(':scope > .cerca-posts');if(!box){box=document.createElement('div');box.className='cerca-posts';t.appendChild(box);}box.innerHTML=posts.map(card).join('');}}catch(e){console.warn('CERCA contenido:',e);}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();})();