(()=>{const BASE='https://pyncovnrhiuwmipyxfae.supabase.co';const KEY='sb_publishable_N6tfAKab0Unt6pIIbnO8YA_wpw_JHbu';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const PROGRAMS=[
 {key:'ninos',match:'niños',title:'CERCA Niños',icon:'🌈'},
 {key:'adolescentes',match:'adolescentes',title:'CERCA Adolescentes',icon:'🧭'},
 {key:'jovenes',match:'jóvenes',title:'CERCA Jóvenes',icon:'🔥'},
 {key:'senoritas',match:'señoritas',title:'CERCA Señoritas',icon:'🌷'},
 {key:'familia',match:'familia',title:'CERCA Familia',icon:'🏠'},
 {key:'programas',match:'programas especiales',title:'Programas especiales',icon:'🎉'}
];
let grouped={};
function youtubeEmbed(u){try{const x=new URL(u);let id='';if(x.hostname.includes('youtu.be'))id=x.pathname.slice(1).split('/')[0];else if(x.hostname.includes('youtube.com'))id=x.searchParams.get('v')||((x.pathname.match(/\/(shorts|embed)\/([^/?]+)/)||[])[2]||'');return id?'https://www.youtube.com/embed/'+encodeURIComponent(id):'';}catch{return'';}}
function media(p){if(!p.media_url)return'';const u=esc(p.media_url),yt=youtubeEmbed(p.media_url);if(p.content_type==='video'){if(yt)return '<div class="cerca-media"><iframe src="'+esc(yt)+'" title="'+esc(p.title)+'" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div>';return '<div class="cerca-media"><video controls preload="metadata" src="'+u+'"></video></div>';}return '<div class="cerca-media"><img src="'+u+'" alt="'+esc(p.title)+'" loading="lazy"></div>';}
function card(p){return '<article class="cerca-post '+(p.featured?'featured':'')+'">'+(p.featured?'<span class="cerca-badge">Destacado</span>':'')+'<h4>'+esc(p.title)+'</h4>'+media(p)+(p.body?'<p>'+esc(p.body).replace(/\n/g,'<br>')+'</p>':'')+(p.link_url?'<a class="cerca-link" href="'+esc(p.link_url)+'" target="_blank" rel="noopener">'+esc(p.link_label||'Ver más')+'</a>':'')+'</article>';}
function programTarget(label){return [...document.querySelectorAll('.program-grid article')].find(a=>(a.querySelector('h3')?.textContent||'').toLowerCase().includes(label));}
function ensureProgramDialog(){let d=document.querySelector('#cerca-program-dialog');if(d)return d;d=document.createElement('dialog');d.id='cerca-program-dialog';d.className='cerca-program-dialog';d.innerHTML='<div class="cerca-program-shell"><button class="cerca-program-close" type="button" aria-label="Cerrar">×</button><div class="cerca-program-head"></div><div class="cerca-program-content"></div></div>';document.body.appendChild(d);d.querySelector('.cerca-program-close').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close();});return d;}
function openProgram(def){const d=ensureProgramDialog(),entry=programTarget(def.match),intro=entry?.querySelector('p')?.textContent||'',posts=grouped[def.key]||[];d.querySelector('.cerca-program-head').innerHTML='<span class="cerca-program-icon">'+def.icon+'</span><p class="eyebrow">PROGRAMA CERCA</p><h2>'+esc(def.title)+'</h2>'+(intro?'<p>'+esc(intro)+'</p>':'');d.querySelector('.cerca-program-content').innerHTML=posts.length?'<div class="cerca-program-posts">'+posts.map(card).join('')+'</div>':'<div class="cerca-empty"><strong>Este espacio está listo.</strong><p>Muy pronto encontrarás aquí mensajes, imágenes, videos y recursos preparados para esta sección.</p></div>';if(typeof d.showModal==='function')d.showModal();else d.setAttribute('open','');}
function wirePrograms(){ensureProgramDialog();PROGRAMS.forEach(def=>{const a=programTarget(def.match);if(!a||a.dataset.cercaReady)return;a.dataset.cercaReady='1';a.classList.add('cerca-program-entry');a.tabIndex=0;a.setAttribute('role','button');a.setAttribute('aria-label','Abrir '+def.title);const c=document.createElement('div');c.className='cerca-program-open';c.innerHTML='<span>Abrir sección</span><b aria-hidden="true">→</b>';a.appendChild(c);a.addEventListener('click',()=>openProgram(def));a.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openProgram(def);}});});}
function updateCounts(){PROGRAMS.forEach(def=>{const a=programTarget(def.match);if(!a)return;let badge=a.querySelector('.cerca-program-count');const n=(grouped[def.key]||[]).length;if(!n){badge?.remove();return;}if(!badge){badge=document.createElement('span');badge.className='cerca-program-count';a.insertBefore(badge,a.querySelector('.cerca-program-open'));}badge.textContent=n+' '+(n===1?'publicación':'publicaciones');});}
function target(section){const map={oracion:()=>document.querySelector('#oracion'),devocionales:()=>document.querySelector('#devocionales .container')};return map[section]?map[section]():null;}
function generalBox(){let box=document.querySelector('#cerca-general-content');if(box)return box;const hero=document.querySelector('.hero');if(!hero)return null;const s=document.createElement('section');s.className='section cerca-general';s.id='cerca-general-content';s.innerHTML='<div class="container"><div class="section-head center"><p class="eyebrow">CERCA HOY</p><h2>Contenido para acompañarte</h2></div><div class="cerca-posts"></div></div>';hero.insertAdjacentElement('afterend',s);return s.querySelector('.cerca-posts');}
function renderNonPrograms(){for(const [section,posts] of Object.entries(grouped)){if(PROGRAMS.some(x=>x.key===section))continue;if(section==='general'){const b=generalBox();if(b)b.innerHTML=posts.map(card).join('');continue;}const t=target(section);if(!t)continue;let box=t.querySelector(':scope > .cerca-posts');if(!box){box=document.createElement('div');box.className='cerca-posts';t.appendChild(box);}box.innerHTML=posts.map(card).join('');}}
async function load(){wirePrograms();try{const r=await fetch(BASE+'/rest/v1/content_posts?select=*&order=featured.desc,starts_at.desc',{headers:{apikey:KEY}});if(!r.ok)throw new Error('HTTP '+r.status);const rows=await r.json();grouped={};rows.forEach(p=>(grouped[p.section]??=[]).push(p));updateCounts();renderNonPrograms();}catch(e){console.warn('CERCA contenido:',e);}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();})();